apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "..fullname" . }}-md
  labels:
    {{- include "..labels" . | nindent 4 }}
data:
  ModuleDescriptor: |
    {{ .Values.moduleDescriptor | default "" | nindent 4 }}
